In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\14-dh0002la\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: numpy>=1.17.3 in c:\users\14-dh0002la\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: pytz>=2017.3 in c:\users\14-dh0002la\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\14-dh0002la\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\14-dh0002la\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [2]:
import pandas as pd

In [3]:
numeros = pd.Series(['10', '20', '10'])
numeros

0    10
1    20
2    10
dtype: object

In [4]:
objetos = pd.Series(['rojo', 'verde', 'azul'])
objetos

0     rojo
1    verde
2     azul
dtype: object

In [5]:
df = pd.DataFrame()

In [6]:
df = pd.DataFrame({"Numeros":numeros})
df

  Numeros
0      10
1      20
2      10

In [7]:
df = pd.DataFrame({"Numeros":numeros,"Objetos":objetos})
df

  Numeros Objetos
0      10    rojo
1      20   verde
2      10    azul

In [10]:
df= pd.read_csv('Data/avengers.csv', sep  = ',')
df

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

In [12]:
print(df.head(5))

                                                 URL  \
0      http://marvel.wikia.com/Henry_Pym_(Earth-616)
1  http://marvel.wikia.com/Janet_van_Dyne_(Earth-...
2  http://marvel.wikia.com/Anthony_Stark_(Earth-616)
3  http://marvel.wikia.com/Robert_Bruce_Banner_(E...
4   http://marvel.wikia.com/Thor_Odinson_(Earth-616)

                        nombre  n_apariciones actual  genero  fecha_inicio  \
0    Henry Jonathan "Hank" Pym           1269    YES    MALE          1963
1               Janet van Dyne           1165    YES  FEMALE          1963
2  Anthony Edward "Tony" Stark           3068    YES    MALE          1963
3          Robert Bruce Banner           2089    YES    MALE          1963
4                 Thor Odinson           2402    YES    MALE          1963

                                               Notes
0  Merged with Ultron in Rage of Ultron Vol. 1. A...
1  Dies in Secret Invasion V1:I8. Actually was se...
2  Death: "Later while under the influence of Imm...
3  Dies in Ghosts of the Future arc. However "he ...
4  Dies in Fear Itself brought back because that'...

In [13]:
print(df.head(10))

                                                 URL  \
0      http://marvel.wikia.com/Henry_Pym_(Earth-616)
1  http://marvel.wikia.com/Janet_van_Dyne_(Earth-...
2  http://marvel.wikia.com/Anthony_Stark_(Earth-616)
3  http://marvel.wikia.com/Robert_Bruce_Banner_(E...
4   http://marvel.wikia.com/Thor_Odinson_(Earth-616)
5  http://marvel.wikia.com/Richard_Jones_(Earth-616)
6  http://marvel.wikia.com/Steven_Rogers_(Earth-616)
7   http://marvel.wikia.com/Clint_Barton_(Earth-616)
8  http://marvel.wikia.com/Pietro_Maximoff_(Earth...
9  http://marvel.wikia.com/Wanda_Maximoff_(Earth-...

                        nombre  n_apariciones actual  genero  fecha_inicio  \
0    Henry Jonathan "Hank" Pym           1269    YES    MALE          1963
1               Janet van Dyne           1165    YES  FEMALE          1963
2  Anthony Edward "Tony" Stark           3068    YES    MALE          1963
3          Robert Bruce Banner           2089    YES    MALE          1963
4                 Thor Odinson           2402    YES    MALE          1963
5       Richard Milhouse Jones            612    YES    MALE          1963
6                Steven Rogers           3458    YES    MALE          1964
7       Clinton Francis Barton           1456    YES    MALE          1965
8              Pietro Maximoff            769    YES    MALE          1965
9               Wanda Maximoff           1214    YES  FEMALE          1965

                                               Notes
0  Merged with Ultron in Rage of Ultron Vol. 1. A...
1  Dies in Secret Invasion V1:I8. Actually was se...
2  Death: "Later while under the influence of Imm...
3  Dies in Ghosts of the Future arc. However "he ...
4  Dies in Fear Itself brought back because that'...
5                                                NaN
6    Dies at the end of Civil War. Later comes back.
7  Dies in exploding Kree ship in Averngers Vol. ...
8  Dies in House of M Vol 1 Issue 7. Later comes ...
9  Dies in Uncanny_Avengers_Vol_1_14. Later comes...

In [14]:
print(df.tail(5))

                                                   URL          nombre  \
168   http://marvel.wikia.com/Eric_Brooks_(Earth-616)#     Eric Brooks
169  http://marvel.wikia.com/Adam_Brashear_(Earth-6...   Adam Brashear
170  http://marvel.wikia.com/Victor_Alvarez_(Earth-...  Victor Alvarez
171     http://marvel.wikia.com/Ava_Ayala_(Earth-616)#       Ava Ayala
172         http://marvel.wikia.com/Kaluu_(Earth-616)#           Kaluu

     n_apariciones actual  genero  fecha_inicio Notes
168            198    YES    MALE          2013   NaN
169             29    YES    MALE          2014   NaN
170             45    YES    MALE          2014   NaN
171             49    YES  FEMALE          2014   NaN
172             35    YES    MALE          2015   NaN

In [15]:
print(len(df.index))#numero de filas

173

In [16]:
print(df.dtypes)

URL              object
nombre           object
n_apariciones     int64
actual           object
genero           object
fecha_inicio      int64
Notes            object
dtype: object

In [17]:
df['fecha_inicio']= df.index
print(df.head(5))

                                                 URL  \
0      http://marvel.wikia.com/Henry_Pym_(Earth-616)
1  http://marvel.wikia.com/Janet_van_Dyne_(Earth-...
2  http://marvel.wikia.com/Anthony_Stark_(Earth-616)
3  http://marvel.wikia.com/Robert_Bruce_Banner_(E...
4   http://marvel.wikia.com/Thor_Odinson_(Earth-616)

                        nombre  n_apariciones actual  genero  fecha_inicio  \
0    Henry Jonathan "Hank" Pym           1269    YES    MALE             0
1               Janet van Dyne           1165    YES  FEMALE             1
2  Anthony Edward "Tony" Stark           3068    YES    MALE             2
3          Robert Bruce Banner           2089    YES    MALE             3
4                 Thor Odinson           2402    YES    MALE             4

                                               Notes
0  Merged with Ultron in Rage of Ultron Vol. 1. A...
1  Dies in Secret Invasion V1:I8. Actually was se...
2  Death: "Later while under the influence of Imm...
3  Dies in Ghosts of the Future arc. However "he ...
4  Dies in Fear Itself brought back because that'...

In [20]:
df.sort_index(axis=0,ascending=False)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,172,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,171,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,170,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,169,NaN
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,168,NaN
...,...,...,...,...,...,...,...
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,4,Dies in Fear Itself brought back because that'...
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,3,"Dies in Ghosts of the Future arc. However ""he ..."
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,2,"Death: ""Later while under the influence of Imm..."
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1,Dies in Secret Invasion V1:I8. Actually was se...
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,0,Merged with Ultron in Rage of Ultron Vol. 1. A...

In [19]:
df.reset_index()

,index,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,0,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1,Dies in Secret Invasion V1:I8. Actually was se...
2,2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,2,"Death: ""Later while under the influence of Imm..."
3,3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,3,"Dies in Ghosts of the Future arc. However ""he ..."
4,4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,4,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...,...
168,168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,168,NaN
169,169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,169,NaN
170,170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,170,NaN
171,171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,171,NaN
172,172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,172,NaN